### ISSUE TITLE
Does it work with new map format?

### ISSUE THREAD

**Issue by Fixer-007** [AndrejIT/map_unexplore#3]
In early Feb 2017 there was map format protocol bump due to merger of lighting fixes, does this tool work on newest engine?

**Comment by AndrejIT** [comment]
I tried with version 4.15.
At first glance, it looks like this Minetest build just don't respect world format specification https://github.com/minetest/minetest/blob/master/doc/world_format.txt

World format bit is 25, as expected but then i read contenth_widh and  params_width as 255, but they should be always 2, according to world format...

**Comment by Fixer-007** [comment]
Info here https://forum.minetest.net/viewtopic.php?f=18&t=16595#p249890

**Comment by AndrejIT** [comment]
Oh! Good, thanks!
I mistaken world format - it really is marked 27 version.
I hope i will find right specifications.

**Comment by AndrejIT** [comment]
Looks like, for some reason map format have two additional xFF bits after "flags" bit.
If i skip those two bits, then map from latest  build is parsed fine.
I pushed new map_unexplore version.

**Comment by Fixer-007** [comment]
https://github.com/minetest/minetest/pull/4682

**Comment by AndrejIT** [comment]
Ok. Thank you @Fixer-007 !

Basically those two bytes (not "bits", i always confuse) contains flags for light calculation resuming.
The way i fixed it first time, there was small chance to get an error.

I improve fix, to read actual map version, instead of guessing bytes.
So now scripts will parse map format 27 but save it back to map format 25.
Right now, this behavior should not create any problems.
